### ISSUE TITLE
nodejs wadoRs.js failing on Promise

### ISSUE THREAD

**Issue by RobertVirtualis** [brunoalvesdefaria/cornerstone-server-rendering#1]
Bruno,

Good day.

When trying to run the node version of wadoRs.js the following promise related error was incurred:

TypeError: Promise is not a constructor

Any help would be most appreciated.

Thanks,

Robert

node ./src/wadoRs.js
dicomweb:http://localhost:8000/image.dcm
/Users/robertklajbor/node_modules/cornerstone-wado-image-loader/dist/cornerstoneWADOImageLoader.min.js:2
!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define("cornerstoneWADOImageLoader",[],t):"object"==typeof exports?exports.cornerstoneWADOImageLoader=t():e.cornerstoneWADOImageLoader=t()}(this,function(){return function(e){var t={};function r(a){if(t[a])return t[a].exports;var n=t[a]={i:a,l:!1,exports:{}};return e[a].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.m=e,r.c=t,r.d=function(e,t,a){r.o(e,t)||Object.defineProperty(e,t,{configurable:!1,enumerable:!0,get:a})},r.r=function(e){Object.defineProperty(e,"__esModule",{value:!0})},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s=63)}([function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0});var a,n=r(56),o=(a=n

TypeError: Promise is not a constructor
    at t.default (/Users/robertklajbor/node_modules/cornerstone-wado-image-loader/dist/cornerstoneWADOImageLoader.min.js:2:39535)
    at Object.load (/Users/robertklajbor/node_modules/cornerstone-wado-image-loader/dist/cornerstoneWADOImageLoader.min.js:2:7370)
    at t.loadImage (/Users/robertklajbor/node_modules/cornerstone-wado-image-loader/dist/cornerstoneWADOImageLoader.min.js:2:18659)
    at s (/Users/robertklajbor/node_modules/cornerstone-core/dist/cornerstone.min.js:2:78829)
    at Object.t.loadImage (/Users/robertklajbor/node_modules/cornerstone-core/dist/cornerstone.min.js:2:78160)
    at loadAndViewImage (/Users/robertklajbor/Documents/GradientQuestions/cornerstone-server-rendering-node/src/wadoRs.js:142:17)
    at Object.<anonymous> (/Users/robertklajbor/Documents/GradientQuestions/cornerstone-server-rendering-node/src/wadoRs.js:192:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by swederik** [comment]
What version of Node is this? Node should support Promises...

**Comment by RobertVirtualis** [comment]
Erik,

v8.11.3

Thanks for you quick response,

Robert

**Comment by swederik** [comment]
Looks like we are using es6-promise package: https://github.com/brunoalvesdefaria/cornerstone-server-rendering/blob/master/src/wadoRs.js#L1

Did you run npm install?

**Comment by RobertVirtualis** [comment]
I reinstalled es6-promise and there is no error but  it does not callBack
from loadImage, it hangs.

Also, in order to get to that point I had to add the following two lines:

const dicomParser = require ( 'dicom-parser');

cornerstoneWADOImageLoader.external.dicomParser = dicomParser;

Thanks

**Comment by RobertVirtualis** [comment]
Also, I am using the node branch.

Will try the master version.

Thanks

**Comment by RobertVirtualis** [comment]
Erik,

The master branch does not support node, which is what I need.

Here is the latest test with the node branch ( with global.Promise =
require('es6-promise'); - latest npm install )

Thanks again,

Robert

dicomweb:http://localhost:8000/image.dcm
TypeError: Promise is not a constructor
xhrRequest.js:9
    at t.default
(/Users/robertklajbor/node_modules/cornerstone-wado-image-loader/dist/cornerstoneWADOImageLoader.min.js:2:39535)
    at Object.load
(/Users/robertklajbor/node_modules/cornerstone-wado-image-loader/dist/cornerstoneWADOImageLoader.min.js:2:7370)
    at t.loadImage
(/Users/robertklajbor/node_modules/cornerstone-wado-image-loader/dist/cornerstoneWADOImageLoader.min.js:2:18659)
    at s
(/Users/robertklajbor/node_modules/cornerstone-core/dist/cornerstone.min.js:2:78829)
    at Object.t.loadImage
(/Users/robertklajbor/node_modules/cornerstone-core/dist/cornerstone.min.js:2:78160)
    at loadAndViewImage
(/Users/robertklajbor/Documents/GradientQuestions/Question1/SendReportImage/SendReportImage_server.js:180:21)
    at Object.saySendReportImage
(/Users/robertklajbor/Documents/GradientQuestions/Question1/SendReportImage/SendReportImage_server.js:230:5)
    at Object.wrapper [as func]
(/Users/robertklajbor/node_modules/lodash/lodash.js:4949:19)
    at /Users/robertklajbor/node_modules/grpc/src/server.js:592:13

**Comment by RobertVirtualis** [comment]
Erik,

All problems resolved.

Fixed by using the version of cornerstoneWADOImageLoader included in the
node branch of the repository.

I am implementing this in a grpc service and it was necessary to comment
out the line "global.Promise = require('es6-promise');" .

Also, as stated previously the lines were add for the dicom-parser:

    const dicomParser = require ( 'dicom-parser');

    cornerstoneWADOImageLoader.external.dicomParser = dicomParser;


Thanks for your help and wish to commend the authors of this work for a
great job.

Regards,

Robert
